'use client';

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useState } from "react";
import { Sidebar } from "@/components/Sidebar";

export default function ArticlesPage() {
  const [activeTab, setActiveTab] = useState('articles');

  return (
    <div className="min-h-screen bg-[#F5F5DC] flex">
      <Sidebar />

      {/* Main Content */}
      <div className="flex-1 ml-64 p-8">
        {/* Header Navigation */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2 text-sm text-gray-600">
            <Link href="/dashboard" className="text-purple-600 text-lg hover:text-purple-700">Dashboard</Link>
            <span className="text-lg">/</span>
            <span className="text-lg">Articles</span>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-gray-600 font-semibold">3 Articles left (15 tokens)</span>
            <Button variant="outline" className="border-2 border-gray-800 hover:bg-gray-100">
              Upgrade Plan
            </Button>
            <Button className="bg-purple-600 hover:bg-purple-700 text-white">
              Create Content
            </Button>
          </div>
        </div>

        <h1 className="text-3xl font-bold mb-4 mt-12">List of articles & categories</h1>
        <p className="text-gray-600 text-lg mb-8">List of all your articles & categories generated by Hellis SEO.</p>

        {/* Tabs */}
        <div className="flex gap-8 border-b border-gray-200 mb-8 mt-24">
          <button 
            onClick={() => setActiveTab('articles')}
            className={`text-lg pb-4 font-medium ${
              activeTab === 'articles' 
                ? 'text-purple-600 border-b-2 border-purple-600' 
                : 'text-gray-500'
            }`}
          >
            Articles
          </button>
          <button 
            onClick={() => setActiveTab('categories')}
            className={`text-lg pb-4 font-medium ${
              activeTab === 'categories' 
                ? 'text-purple-600 border-b-2 border-purple-600' 
                : 'text-gray-500'
            }`}
          >
            Categories
          </button>
        </div>

        {/* Content */}
        {activeTab === 'articles' ? (
          <div className="bg-purple-50 rounded-xl p-8 flex flex-col items-center justify-center">
            <p className="text-purple-600 text-lg mb-4">
              You don't have any articles. Select one of our models and create outstanding content.
            </p>
            <Button className="bg-purple-600 hover:bg-purple-700 text-white">
              Create Content
            </Button>
          </div>
        ) : (
          <div className="bg-purple-50 rounded-xl p-8 flex flex-col items-center justify-center">
            <p className="text-purple-600 text-lg mb-4">
              You don't have any categories yet. Select one of our models and create outstanding content.
            </p>
            <Button className="bg-purple-600 hover:bg-purple-700 text-white">
              Create Category Description
            </Button>
          </div>
        )}
      </div>
    </div>
  );
}
