'use client';

import { Button } from "@/components/ui/button";
import Link from "next/link";
import { useState } from "react";
import { Sidebar } from "@/components/Sidebar";
import { useArticles, Article } from "@/store/useArticles";

export default function ArticlesPage() {
  const [activeTab, setActiveTab] = useState('articles');
  const { articles, removeArticle } = useArticles();

  return (
    <div className="min-h-screen bg-[#F5F5DC] flex">
      <Sidebar />

      {/* Main Content */}
      <div className="flex-1 ml-64 p-8">
        {/* Header Navigation */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-2 text-sm text-gray-600">
            <Link href="/dashboard" className="text-purple-600 text-lg hover:text-purple-700">Dashboard</Link>
            <span className="text-lg">/</span>
            <span className="text-lg">Articles</span>
          </div>
          <div className="flex items-center gap-4">
            <span className="text-gray-600 font-semibold">3 Articles left (15 tokens)</span>
            <Link href="/subscription">
              <Button variant="outline" className="border-2 border-gray-800 hover:bg-purple-200">
                Upgrade Plan
              </Button>
            </Link>
            <Link href="/create-content">
              <Button className="p-3 w-full bg-purple-600 text-white py-2 rounded-lg hover:bg-purple-700">
                Create Content
              </Button>
            </Link>
          </div>
        </div>

        <h1 className="text-3xl font-bold mb-4 mt-12">List of articles & categories</h1>
        <p className="text-gray-600 text-lg mb-8">List of all your articles & categories generated by Hellis SEO.</p>

        {/* Tabs */}
        <div className="flex gap-8 border-b border-gray-400 mb-8 mt-24">
          <button 
            onClick={() => setActiveTab('articles')}
            className={`text-lg pb-4 font-medium ${
              activeTab === 'articles' 
                ? 'text-purple-600 border-b-2 border-purple-600' 
                : 'text-gray-600'
            }`}
          >
            Articles
          </button>
          <button 
            onClick={() => setActiveTab('categories')}
            className={`text-lg pb-4 font-medium ${
              activeTab === 'categories' 
                ? 'text-purple-600 border-b-2 border-purple-600' 
                : 'text-gray-600'
            }`}
          >
            Categories
          </button>
        </div>

        {/* Content */}
        {activeTab === 'articles' ? (
          <>
            {/* Search and Order */}
            <div className="flex justify-between mb-6">
              <input
                type="text"
                placeholder="Search by project or title..."
                className="w-96 px-4 py-2 border rounded-lg"
              />
              <Button variant="outline">Order By ↕</Button>
            </div>

            {/* Table */}
            <div className="bg-white rounded-lg shadow">
              {/* Table Header */}
              <div className="grid grid-cols-6 gap-4 p-4 border-b text-gray-600">
                <div>Project</div>
                <div className="col-span-2">Title</div>
                <div>Words</div>
                <div>Characters</div>
                <div className="flex justify-between">
                  <span>Status</span>
                  <span>Delete</span>
                </div>
              </div>

              {/* Table Content */}
              <div>
                {articles.map((article) => (
                  <div key={article.id} className="grid grid-cols-6 gap-4 p-4 border-b hover:bg-gray-50">
                    <div className="text-purple-600">
                      <Link href={`/projects/${encodeURIComponent(article.project)}/${encodeURIComponent(article.title)}`} className="hover:underline">
                        {article.project}
                      </Link>
                    </div>
                    <div className="col-span-2">
                      <Link href={`/projects/${encodeURIComponent(article.project)}/${encodeURIComponent(article.title)}`} className="hover:underline">
                        {article.title}
                      </Link>
                    </div>
                    <div>{article.words}</div>
                    <div>{article.characters}</div>
                    <div className="flex justify-between items-center">
                      <span className="px-3 py-1 bg-green-100 text-green-600 rounded-full text-sm">
                        {article.status}
                      </span>
                      <button 
                        onClick={() => removeArticle(article.id)}
                        className="text-red-500 hover:text-red-600"
                      >
                        Delete
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </>
        ) : (
          <div className="max-w-5xl mx-auto bg-purple-50 rounded-xl p-8 flex flex-col items-center justify-center">
            <p className="text-purple-600 text-lg mb-4">
              You don't have any categories yet. Select one of our models and create outstanding content.
            </p>
            <Link href="/create-content/category-description">
              <Button className="mt-8 bg-purple-600 hover:bg-purple-700 text-white">
                Create Category Description
              </Button>
            </Link>
          </div>
        )}
      </div>
    </div>
  );
}
